services:
  prometheus:
    image: prom/prometheus:v3.2.1
    container_name: prometheus
    restart: always
    ports:
      - "9090:9090"
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    
  # grafana:
  #   image: grafana/grafana:8.3.3
  #   container_name: grafana
  #   restart: always
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - grafana-data:/var/lib/grafana


volumes:
  prometheus-data:
  # grafana-data:

